version: "3.7"
services:
  db:
    image: 'postgres'
    ports: 5432:5432
    environment:
      POSTGRES_PASSWORD: 123456

  web: 
    command: diesel migration run && vos run --listen-to-all-network --port 8000
    build: 
      context: .
    environment:
      DATABASE_URL: postgres://postgres:123456@db/postgres
      DISABLE_RECAPTCHA: t 
    depends_on:
      - db

  nginx:
    image: 'nginx'
    ports: 1234:80
    volumes:
      - ${pwd}/deploy/nginx.conf:/etc/nginx/nginx.conf:ro
