version: "3.7"
services:
  db:
    image: 'postgres'
    ports: 5432:5432
    environment:
      POSTGRES_PASSWORD: 123456

  web: 
    command: diesel migration run && vos run --listen-to-all-network --port 8000
    build: 
      context: .
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: postgres://postgres:123456@db/postgres
      DISABLE_RECAPTCHA: t 
    depends_on:
      - db
